#include <stdint.h>

/* PD0 VBAT Register Base Addresses */
#define VBATALL_BASE  0x1A609000
#define VBATSEC_BASE  0x1A60A000
#define VBATPD4_BASE  0x1A60B000
#define VBATSEC2_BASE 0x1A60C000

typedef struct
{
    volatile uint32_t GPIO_CTRL;    /* 0x00 */
    volatile uint32_t TIMER_CLKSEL; /* 0x04 */
    volatile uint32_t PWR_CTRL;     /* 0x08 */
    volatile uint32_t RET_CTRL;     /* 0x0C */
    volatile uint32_t RTC_CLK_EN;   /* 0x10 */
#if defined(ENSEMBLE_SOC_E1C)
    volatile uint32_t RTCB_CLK_EN; /* 0x14 */
#endif
} VBATALL_Type;

/* GPIO_CTRL register bit fields */
#define VBATALL_GPIO_CTRL_VOLT_LEVEL_Pos    (0U)
#define VBATALL_GPIO_CTRL_VOLT_LEVEL_Msk    (1U << VBATALL_GPIO_CTRL_VOLT_LEVEL_Pos)
#define VBATALL_GPIO_CTRL_VOLT_LEVEL_3V3    (0U << VBATALL_GPIO_CTRL_VOLT_LEVEL_Pos)
#define VBATALL_GPIO_CTRL_VOLT_LEVEL_1V8    (1U << VBATALL_GPIO_CTRL_VOLT_LEVEL_Pos)
#define VBATALL_GPIO_CTRL_GPIO_MUX_CTRL_Pos (4U)
#define VBATALL_GPIO_CTRL_GPIO_MUX_CTRL_Msk (1U << VBATALL_GPIO_CTRL_GPIO_MUX_CTRL_Pos)

/* TIMER_CLKSEL register bit fields for LPTIMER channels 0-3 */
#define VBATALL_TIMER_CLKSEL_SEL1_Pos (0U)
#define VBATALL_TIMER_CLKSEL_SEL1_Msk (0x3U << VBATALL_TIMER_CLKSEL_SEL1_Pos)
#define VBATALL_TIMER_CLKSEL_SEL2_Pos (4U)
#define VBATALL_TIMER_CLKSEL_SEL2_Msk (0x3U << VBATALL_TIMER_CLKSEL_SEL2_Pos)
#define VBATALL_TIMER_CLKSEL_SEL3_Pos (8U)
#define VBATALL_TIMER_CLKSEL_SEL3_Msk (0x3U << VBATALL_TIMER_CLKSEL_SEL3_Pos)
#define VBATALL_TIMER_CLKSEL_SEL4_Pos (12U)
#define VBATALL_TIMER_CLKSEL_SEL4_Msk (0x3U << VBATALL_TIMER_CLKSEL_SEL4_Pos)
#define VBATALL_TIMER_CLKSEL_SEL_32K  (0U) // LPTIMER at 32768Hz (LFRC or LFXO chosen by VBATSEC_SEL_32K)
#define VBATALL_TIMER_CLKSEL_SEL_128K (1U) // LPTIMER at 131072Hz (LFRCx4)
#define VBATALL_TIMER_CLKSEL_SEL_EXT  (2U) // LPTIMER uses external pin as clock
#define VBATALL_TIMER_CLKSEL_SEL_CASC (3U) // 64-bit mode, LPTIMER0+1 or LPTIMER2+3

/* PWR_CTRL register bit fields */
#define VBATALL_PWR_CTRL_TX_DPHY_PWR_MASK_Pos         (0U)
#define VBATALL_PWR_CTRL_TX_DPHY_PWR_MASK_Msk         (1U << VBATALL_PWR_CTRL_TX_DPHY_PWR_MASK_Pos)
#define VBATALL_PWR_CTRL_TX_DPHY_ISO_Pos              (1U)
#define VBATALL_PWR_CTRL_TX_DPHY_ISO_Msk              (1U << VBATALL_PWR_CTRL_TX_DPHY_ISO_Pos)
#define VBATALL_PWR_CTRL_RX_DPHY_PWR_MASK_Pos         (4U)
#define VBATALL_PWR_CTRL_RX_DPHY_PWR_MASK_Msk         (1U << VBATALL_PWR_CTRL_RX_DPHY_PWR_MASK_Pos)
#define VBATALL_PWR_CTRL_RX_DPHY_ISO_Pos              (5U)
#define VBATALL_PWR_CTRL_RX_DPHY_ISO_Msk              (1U << VBATALL_PWR_CTRL_RX_DPHY_ISO_Pos)
#define VBATALL_PWR_CTRL_DPHY_PLL_PWR_MASK_Pos        (8U)
#define VBATALL_PWR_CTRL_DPHY_PLL_PWR_MASK_Msk        (1U << VBATALL_PWR_CTRL_DPHY_PLL_PWR_MASK_Pos)
#define VBATALL_PWR_CTRL_DPHY_PLL_ISO_Pos             (9U)
#define VBATALL_PWR_CTRL_DPHY_PLL_ISO_Msk             (1U << VBATALL_PWR_CTRL_DPHY_PLL_ISO_Pos)
#define VBATALL_PWR_CTRL_DPHY_VPH_1P8_PWR_BYP_EN_Pos  (12U)
#define VBATALL_PWR_CTRL_DPHY_VPH_1P8_PWR_BYP_EN_Msk  (1U << VBATALL_PWR_CTRL_DPHY_VPH_1P8_PWR_BYP_EN_Pos)
#define VBATALL_PWR_CTRL_DPHY_VPH_1P8_PWR_BYP_VAL_Pos (13U)
#define VBATALL_PWR_CTRL_DPHY_VPH_1P8_PWR_BYP_VAL_Msk (1U << VBATALL_PWR_CTRL_DPHY_VPH_1P8_PWR_BYP_VAL_Pos)
#define VBATALL_PWR_CTRL_UPHY_PWR_MASK_Pos            (16U)
#define VBATALL_PWR_CTRL_UPHY_PWR_MASK_Msk            (1U << VBATALL_PWR_CTRL_UPHY_PWR_MASK_Pos)
#define VBATALL_PWR_CTRL_UPHY_ISO_Pos                 (17U)
#define VBATALL_PWR_CTRL_UPHY_ISO_Msk                 (1U << VBATALL_PWR_CTRL_UPHY_ISO_Pos)
#define VBATALL_PWR_CTRL_VREG_AUX_1_1V8_EN_Pos        (24U)
#define VBATALL_PWR_CTRL_VREG_AUX_1_1V8_EN_Msk        (1U << VBATALL_PWR_CTRL_VREG_AUX_1_1V8_EN_Pos)
#define VBATALL_PWR_CTRL_VREG_AUX_2_1V8_EN_Pos        (25U)
#define VBATALL_PWR_CTRL_VREG_AUX_2_1V8_EN_Msk        (1U << VBATALL_PWR_CTRL_VREG_AUX_2_1V8_EN_Pos)

#if defined(ENSEMBLE_SOC_E1C)
/* RET_CTRL register bit fields for Ensemble E1C */
#define VBATALL_RET_CTRL_BKRAM_RET_EN_Pos  (0U)
#define VBATALL_RET_CTRL_BKRAM_RET_EN_Msk  (1U << VBATALL_RET_CTRL_BKRAM_RET_EN_Pos)
#define VBATALL_RET_CTRL_HETCM_RET1_EN_Pos (1U)
#define VBATALL_RET_CTRL_HETCM_RET1_EN_Msk (1U << VBATALL_RET_CTRL_HETCM_RET1_EN_Pos)
#define VBATALL_RET_CTRL_HETCM_RET2_EN_Pos (2U)
#define VBATALL_RET_CTRL_HETCM_RET2_EN_Msk (1U << VBATALL_RET_CTRL_HETCM_RET2_EN_Pos)
#define VBATALL_RET_CTRL_HETCM_RET3_EN_Pos (3U)
#define VBATALL_RET_CTRL_HETCM_RET3_EN_Msk (1U << VBATALL_RET_CTRL_HETCM_RET3_EN_Pos)
#define VBATALL_RET_CTRL_HETCM_RET4_EN_Pos (4U)
#define VBATALL_RET_CTRL_HETCM_RET4_EN_Msk (1U << VBATALL_RET_CTRL_HETCM_RET4_EN_Pos)
#define VBATALL_RET_CTRL_HETCM_RET5_EN_Pos (5U)
#define VBATALL_RET_CTRL_HETCM_RET5_EN_Msk (1U << VBATALL_RET_CTRL_HETCM_RET5_EN_Pos)
#define VBATALL_RET_CTRL_HETCM_RET6_EN_Pos (6U)
#define VBATALL_RET_CTRL_HETCM_RET6_EN_Msk (1U << VBATALL_RET_CTRL_HETCM_RET6_EN_Pos)
#elif defined(ENSEMBLE_SOC_GEN2)
/* RET_CTRL register bit fields for Ensemble E4/E6/E8 */
#define VBATALL_RET_CTRL_BKRAM_RET_MASK_Pos   (0U)
#define VBATALL_RET_CTRL_BKRAM_RET_MASK_Msk   (1U << VBATALL_RET_CTRL_BKRAM_RET_MASK_Pos)
#define VBATALL_RET_CTRL_BKRAM_RET_FORCE_Pos  (1U)
#define VBATALL_RET_CTRL_BKRAM_RET_FORCE_Msk  (1U << VBATALL_RET_CTRL_BKRAM_RET_FORCE_Pos)
#define VBATALL_RET_CTRL_HETCM_RET1_MASK_Pos  (4U)
#define VBATALL_RET_CTRL_HETCM_RET1_MASK_Msk  (1U << VBATALL_RET_CTRL_HETCM_RET1_MASK_Pos)
#define VBATALL_RET_CTRL_HETCM_RET1_FORCE_Pos (5U)
#define VBATALL_RET_CTRL_HETCM_RET1_FORCE_Msk (1U << VBATALL_RET_CTRL_HETCM_RET1_FORCE_Pos)
#define VBATALL_RET_CTRL_HETCM_RET2_MASK_Pos  (6U)
#define VBATALL_RET_CTRL_HETCM_RET2_MASK_Msk  (1U << VBATALL_RET_CTRL_HETCM_RET2_MASK_Pos)
#define VBATALL_RET_CTRL_HETCM_RET2_FORCE_Pos (7U)
#define VBATALL_RET_CTRL_HETCM_RET2_FORCE_Msk (1U << VBATALL_RET_CTRL_HETCM_RET2_FORCE_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET1_MASK_Pos  (8U)
#define VBATALL_RET_CTRL_SRAM0_RET1_MASK_Msk  (1U << VBATALL_RET_CTRL_SRAM0_RET1_MASK_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET1_FORCE_Pos (9U)
#define VBATALL_RET_CTRL_SRAM0_RET1_FORCE_Msk (1U << VBATALL_RET_CTRL_SRAM0_RET1_FORCE_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET2_MASK_Pos  (10U)
#define VBATALL_RET_CTRL_SRAM0_RET2_MASK_Msk  (1U << VBATALL_RET_CTRL_SRAM0_RET2_MASK_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET2_FORCE_Pos (11U)
#define VBATALL_RET_CTRL_SRAM0_RET2_FORCE_Msk (1U << VBATALL_RET_CTRL_SRAM0_RET2_FORCE_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET3_MASK_Pos  (12U)
#define VBATALL_RET_CTRL_SRAM0_RET3_MASK_Msk  (1U << VBATALL_RET_CTRL_SRAM0_RET3_MASK_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET3_FORCE_Pos (13U)
#define VBATALL_RET_CTRL_SRAM0_RET3_FORCE_Msk (1U << VBATALL_RET_CTRL_SRAM0_RET3_FORCE_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET4_MASK_Pos  (14U)
#define VBATALL_RET_CTRL_SRAM0_RET4_MASK_Msk  (1U << VBATALL_RET_CTRL_SRAM0_RET4_MASK_Pos)
#define VBATALL_RET_CTRL_SRAM0_RET4_FORCE_Pos (15U)
#define VBATALL_RET_CTRL_SRAM0_RET4_FORCE_Msk (1U << VBATALL_RET_CTRL_SRAM0_RET4_FORCE_Pos)
#define VBATALL_RET_CTRL_SRAM1_RET_MASK_Pos   (16U)
#define VBATALL_RET_CTRL_SRAM1_RET_MASK_Msk   (1U << VBATALL_RET_CTRL_SRAM1_RET_MASK_Pos)
#define VBATALL_RET_CTRL_SRAM1_RET_FORCE_Pos  (17U)
#define VBATALL_RET_CTRL_SRAM1_RET_FORCE_Msk  (1U << VBATALL_RET_CTRL_SRAM1_RET_FORCE_Pos)
#else
/* RET_CTRL register bit fields for Ensemble E1/E3/E5/E7 */
#define VBATALL_RET_CTRL_BKRAM_RET_MASK_Pos   (0U)
#define VBATALL_RET_CTRL_BKRAM_RET_MASK_Msk   (1U << VBATALL_RET_CTRL_BKRAM_RET_MASK_Pos)
#define VBATALL_RET_CTRL_BKRAM_RET_FORCE_Pos  (1U)
#define VBATALL_RET_CTRL_BKRAM_RET_FORCE_Msk  (1U << VBATALL_RET_CTRL_BKRAM_RET_FORCE_Pos)
#define VBATALL_RET_CTRL_HETCM_RET1_MASK_Pos  (4U)
#define VBATALL_RET_CTRL_HETCM_RET1_MASK_Msk  (1U << VBATALL_RET_CTRL_HETCM_RET1_MASK_Pos)
#define VBATALL_RET_CTRL_HETCM_RET1_FORCE_Pos (5U)
#define VBATALL_RET_CTRL_HETCM_RET1_FORCE_Msk (1U << VBATALL_RET_CTRL_HETCM_RET1_FORCE_Pos)
#define VBATALL_RET_CTRL_HETCM_RET2_MASK_Pos  (6U)
#define VBATALL_RET_CTRL_HETCM_RET2_MASK_Msk  (1U << VBATALL_RET_CTRL_HETCM_RET2_MASK_Pos)
#define VBATALL_RET_CTRL_HETCM_RET2_FORCE_Pos (7U)
#define VBATALL_RET_CTRL_HETCM_RET2_FORCE_Msk (1U << VBATALL_RET_CTRL_HETCM_RET2_FORCE_Pos)
#endif

/* RTC_CLK_EN and RTCB_CLK_EN register bit fields */
#define VBATALL_RTC_CLK_EN_Pos (0U)
#define VBATALL_RTC_CLK_EN_Msk (1U << VBATALL_RTC_CLK_EN_Pos)

typedef struct
{
    volatile uint32_t MISC_CTRL;       /* 0x00 */
    volatile uint32_t PWR_CTRL;        /* 0x04 */
    volatile uint32_t WKUP_CTRL;       /* 0x08 */
    volatile const uint32_t RESERVED1; /* 0x0C */
    volatile const uint32_t RESERVED2; /* 0x10 */
    volatile const uint32_t RESERVED3; /* 0x14 */
    volatile uint32_t RET_CTRL;        /* 0x18 */
    volatile const uint32_t RESERVED4; /* 0x1C */
    volatile uint32_t CM55_HE_NS_VTOR; /* 0x20 */
    volatile uint32_t CM55_HE_SE_VTOR; /* 0x24 */
    volatile const uint32_t RESERVED5; /* 0x28 */
    volatile const uint32_t RESERVED6; /* 0x2C */
    volatile uint32_t DCDC_REG1;       /* 0x30 */
    volatile uint32_t DCDC_REG2;       /* 0x34 */
    volatile uint32_t VBAT_ANA_REG1;   /* 0x38 */
    volatile uint32_t VBAT_ANA_REG2;   /* 0x3C */
    volatile uint32_t VBAT_ANA_REG3;   /* 0x40 */
} VBATSEC_Type;

/* MISC_CTRL register bit fields */
#define VBATSEC_MISC_CTRL_SEL_32K_Pos (0U)
#define VBATSEC_MISC_CTRL_SEL_32K_Msk (1U << VBATSEC_MISC_CTRL_SEL_32K_Pos)

/* PWR_CTRL register bit fields */
#define VBATSEC_PWR_CTRL_PD1_PWR_CTRL_Pos              (0U)
#define VBATSEC_PWR_CTRL_PD1_PWR_CTRL_Msk              (1U << VBATSEC_PWR_CTRL_PD1_PWR_CTRL_Pos)
#define VBATSEC_PWR_CTRL_MRAM_EFUSE_VDD18_Pos          (4U)
#define VBATSEC_PWR_CTRL_MRAM_EFUSE_VDD18_Msk          (1U << VBATSEC_PWR_CTRL_MRAM_EFUSE_VDD18_Pos)
#define VBATSEC_PWR_CTRL_SECENC_EFUSE_VDD18_Pos        (5U)
#define VBATSEC_PWR_CTRL_SECENC_EFUSE_VDD18_Msk        (1U << VBATSEC_PWR_CTRL_SECENC_EFUSE_VDD18_Pos)
#define VBATSEC_PWR_CTRL_MBIST_EFUSE_VDD18_Pos         (6U)
#define VBATSEC_PWR_CTRL_MBIST_EFUSE_VDD18_Msk         (1U << VBATSEC_PWR_CTRL_MBIST_EFUSE_VDD18_Pos)
#define VBATSEC_PWR_CTRL_SRAM0_PWR_MASK_Pos            (8U)
#define VBATSEC_PWR_CTRL_SRAM0_PWR_MASK_Msk            (1U << VBATSEC_PWR_CTRL_SRAM0_PWR_MASK_Pos)
#define VBATSEC_PWR_CTRL_SRAM0_ISO_Pos                 (9U)
#define VBATSEC_PWR_CTRL_SRAM0_ISO_Msk                 (1U << VBATSEC_PWR_CTRL_SRAM0_ISO_Pos)
#define VBATSEC_PWR_CTRL_SRAM1_PWR_MASK_Pos            (12U)
#define VBATSEC_PWR_CTRL_SRAM1_PWR_MASK_Msk            (1U << VBATSEC_PWR_CTRL_SRAM1_PWR_MASK_Pos)
#define VBATSEC_PWR_CTRL_SRAM1_ISO_Pos                 (13U)
#define VBATSEC_PWR_CTRL_SRAM1_ISO_Msk                 (1U << VBATSEC_PWR_CTRL_SRAM1_ISO_Pos)
#define VBATSEC_PWR_CTRL_MRAM_VDDA_1P8_PWR_BYP_EN_Pos  (16U)
#define VBATSEC_PWR_CTRL_MRAM_VDDA_1P8_PWR_BYP_EN_Msk  (1U << VBATSEC_PWR_CTRL_MRAM_VDDA_1P8_PWR_BYP_EN_Pos)
#define VBATSEC_PWR_CTRL_MRAM_VDDA_1P8_PWR_BYP_VAL_Pos (17U)
#define VBATSEC_PWR_CTRL_MRAM_VDDA_1P8_PWR_BYP_VAL_Msk (1U << VBATSEC_PWR_CTRL_MRAM_VDDA_1P8_PWR_BYP_VAL_Pos)

/* WKUP_CTRL register bit fields */
#define VBATSEC_WKUP_CTRL_RTCA_Pos      (5U)
#define VBATSEC_WKUP_CTRL_RTCA_Msk      (1U << VBATSEC_WKUP_CTRL_RTCA_Pos)
#define VBATSEC_WKUP_CTRL_LPCMP_Pos     (6U)
#define VBATSEC_WKUP_CTRL_LPCMP_Msk     (1U << VBATSEC_WKUP_CTRL_LPCMP_Pos)
#define VBATSEC_WKUP_CTRL_BROWN_OUT_Pos (7U)
#define VBATSEC_WKUP_CTRL_BROWN_OUT_Msk (1U << VBATSEC_WKUP_CTRL_BROWN_OUT_Pos)
#define VBATSEC_WKUP_CTRL_LPTIMER_Pos   (8U)
#define VBATSEC_WKUP_CTRL_LPTIMER_Msk   (0xFU << VBATSEC_WKUP_CTRL_LPTIMER_Pos)
#define VBATSEC_WKUP_CTRL_LPTIMER0_EN   (1U << VBATSEC_WKUP_CTRL_LPTIMER_Pos)
#define VBATSEC_WKUP_CTRL_LPTIMER1_EN   (2U << VBATSEC_WKUP_CTRL_LPTIMER_Pos)
#define VBATSEC_WKUP_CTRL_LPTIMER2_EN   (4U << VBATSEC_WKUP_CTRL_LPTIMER_Pos)
#define VBATSEC_WKUP_CTRL_LPTIMER3_EN   (8U << VBATSEC_WKUP_CTRL_LPTIMER_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO_Pos    (16U)
#define VBATSEC_WKUP_CTRL_LPGPIO_Msk    (0xFFU << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO0_EN    (0x01U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO1_EN    (0x02U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO2_EN    (0x04U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO3_EN    (0x08U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO4_EN    (0x10U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO5_EN    (0x20U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO6_EN    (0x40U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)
#define VBATSEC_WKUP_CTRL_LPGPIO7_EN    (0x80U << VBATSEC_WKUP_CTRL_LPGPIO_Pos)

/* RET_CTRL register bit fields */
#define VBATSEC_RET_CTRL_FWRAM_RET_MASK_Pos   (0U)
#define VBATSEC_RET_CTRL_FWRAM_RET_MASK_Msk   (1U << VBATSEC_RET_CTRL_FWRAM_RET_MASK_Pos)
#define VBATSEC_RET_CTRL_FWRAM_RET_FORCE_Pos  (1U)
#define VBATSEC_RET_CTRL_FWRAM_RET_FORCE_Msk  (1U << VBATSEC_RET_CTRL_FWRAM_RET_FORCE_Pos)
#define VBATSEC_RET_CTRL_SETCM_RET1_MASK_Pos  (4U)
#define VBATSEC_RET_CTRL_SETCM_RET1_MASK_Msk  (1U << VBATSEC_RET_CTRL_SETCM_RET1_MASK_Pos)
#define VBATSEC_RET_CTRL_SETCM_RET1_FORCE_Pos (5U)
#define VBATSEC_RET_CTRL_SETCM_RET1_FORCE_Msk (1U << VBATSEC_RET_CTRL_SETCM_RET1_FORCE_Pos)
#define VBATSEC_RET_CTRL_SETCM_RET2_MASK_Pos  (6U)
#define VBATSEC_RET_CTRL_SETCM_RET2_MASK_Msk  (1U << VBATSEC_RET_CTRL_SETCM_RET2_MASK_Pos)
#define VBATSEC_RET_CTRL_SETCM_RET2_FORCE_Pos (7U)
#define VBATSEC_RET_CTRL_SETCM_RET2_FORCE_Msk (1U << VBATSEC_RET_CTRL_SETCM_RET2_FORCE_Pos)

/* CM55_HE_NS_VTOR register bit fields */
#define VBATSEC_CM55_HE_NS_VTOR_Pos (7U)
#define VBATSEC_CM55_HE_NS_VTOR_Msk (0x1FFFFFFU << VBATSEC_CM55_HE_NS_VTOR_Pos)

/* CM55_HE_SE_VTOR register bit fields */
#define VBATSEC_CM55_HE_SE_VTOR_Pos (7U)
#define VBATSEC_CM55_HE_SE_VTOR_Msk (0x1FFFFFFU << VBATSEC_CM55_HE_SE_VTOR_Pos)

/* DCDC_REG1 register bit fields */
#define VBATSEC_DCDC_REG1_DCDC_TRIM_VOUT_Pos (3U)
#define VBATSEC_DCDC_REG1_DCDC_TRIM_VOUT_Msk (0x3FU << VBATSEC_DCDC_REG1_DCDC_TRIM_VOUT_Pos)

/* DCDC_REG2 register bit fields */
#define VBATSEC_DCDC_REG2_DCDC_PFM_EN_Pos (23U)
#define VBATSEC_DCDC_REG2_DCDC_PFM_EN_Msk (1U << VBATSEC_DCDC_REG2_DCDC_PFM_EN_Pos)

/* VBAT_ANA_REG1 register bit fields */
#define VBATSEC_VBAT_ANA_REG1_RET_LDO_VBAT_EN_Pos  (8U)
#define VBATSEC_VBAT_ANA_REG1_RET_LDO_VBAT_EN_Msk  (1U << VBATSEC_VBAT_ANA_REG1_RET_LDO_VBAT_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_RET_LDO_MAIN_EN_Pos  (10U)
#define VBATSEC_VBAT_ANA_REG1_RET_LDO_MAIN_EN_Msk  (1U << VBATSEC_VBAT_ANA_REG1_RET_LDO_MAIN_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_XTAL32K_EN_Pos       (12U)
#define VBATSEC_VBAT_ANA_REG1_XTAL32K_EN_Msk       (1U << VBATSEC_VBAT_ANA_REG1_XTAL32K_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_CLK_EN_Pos     (14U)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_CLK_EN_Msk     (1U << VBATSEC_VBAT_ANA_REG1_LPCMP_CLK_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_XTAL32K_CAP_CTRL_Pos (19U)
#define VBATSEC_VBAT_ANA_REG1_XTAL32K_CAP_CTRL_Msk (0x3FU << VBATSEC_VBAT_ANA_REG1_XTAL32K_CAP_CTRL_Pos)
#define VBATSEC_VBAT_ANA_REG1_BOR_EN_Pos           (25U)
#define VBATSEC_VBAT_ANA_REG1_BOR_EN_Msk           (1U << VBATSEC_VBAT_ANA_REG1_BOR_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_BOR_HYST_Pos         (26U)
#define VBATSEC_VBAT_ANA_REG1_BOR_HYST_Msk         (7U << VBATSEC_VBAT_ANA_REG1_BOR_HYST_Pos)
#define VBATSEC_VBAT_ANA_REG1_BOR_THRESH_Pos       (29U)
#define VBATSEC_VBAT_ANA_REG1_BOR_THRESH_Msk       (7U << VBATSEC_VBAT_ANA_REG1_BOR_THRESH_Pos)

/* VBAT_ANA_REG2 register bit fields */
#define VBATSEC_VBAT_ANA_REG2_MRAM_LDO_EN_Pos          (5U)
#define VBATSEC_VBAT_ANA_REG2_MRAM_LDO_EN_Msk          (1U << VBATSEC_VBAT_ANA_REG2_MRAM_LDO_EN_Pos)
#define VBATSEC_VBAT_ANA_REG2_OSC_DIV_CTRL_ACTIVE_Pos  (11U)
#define VBATSEC_VBAT_ANA_REG2_OSC_DIV_CTRL_ACTIVE_Msk  (7U << VBATSEC_VBAT_ANA_REG2_OSC_DIV_CTRL_ACTIVE_Pos)
#define VBATSEC_VBAT_ANA_REG2_OSC_DIV_CTRL_STANDBY_Pos (19U)
#define VBATSEC_VBAT_ANA_REG2_OSC_DIV_CTRL_STANDBY_Msk (7U << VBATSEC_VBAT_ANA_REG2_OSC_DIV_CTRL_STANDBY_Pos)
#define VBATSEC_VBAT_ANA_REG2_ANA_PERIPH_EN_Pos        (22U)
#define VBATSEC_VBAT_ANA_REG2_ANA_PERIPH_EN_Msk        (3U << VBATSEC_VBAT_ANA_REG2_ANA_PERIPH_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_EN_Pos             (24U)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_EN_Msk             (1U << VBATSEC_VBAT_ANA_REG1_LPCMP_EN_Pos)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_IN_P_SEL_Pos       (25U)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_IN_P_SEL_Msk       (3U << VBATSEC_VBAT_ANA_REG1_LPCMP_IN_P_SEL_Pos)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_IN_N_SEL_Pos       (27U)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_IN_N_SEL_Msk       (3U << VBATSEC_VBAT_ANA_REG1_LPCMP_IN_N_SEL_Pos)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_HYST_Pos           (29U)
#define VBATSEC_VBAT_ANA_REG1_LPCMP_HYST_Msk           (7U << VBATSEC_VBAT_ANA_REG1_LPCMP_HYST_Pos)

/* VBAT_ANA_REG3 register bit fields */
#define VBATSEC_VBAT_ANA_REG3_BOD_EN_Pos        (8U)
#define VBATSEC_VBAT_ANA_REG3_BOD_EN_Msk        (1U << VBATSEC_VBAT_ANA_REG3_BOD_EN_Pos)
#define VBATSEC_VBAT_ANA_REG3_BOD_HYST_Pos      (9U)
#define VBATSEC_VBAT_ANA_REG3_BOD_HYST_Msk      (7U << VBATSEC_VBAT_ANA_REG3_BOD_HYST_Pos)
#define VBATSEC_VBAT_ANA_REG3_BOD_THRESH_Pos    (12U)
#define VBATSEC_VBAT_ANA_REG3_BOD_THRESH_Msk    (7U << VBATSEC_VBAT_ANA_REG3_BOD_THRESH_Pos)
#define VBATSEC_VBAT_ANA_REG3_LPCMP_CLK_SEL_Pos (31U)
#define VBATSEC_VBAT_ANA_REG3_LPCMP_CLK_SEL_Msk (1U << VBATSEC_VBAT_ANA_REG3_LPCMP_CLK_SEL_Pos)

typedef struct
{
    volatile uint32_t RET_CTRL;        /* 0x00 */
    volatile const uint32_t RESERVED1; /* 0x04 */
    volatile uint32_t PWR_CTRL;        /* 0x08 */
} VBATPD4_Type;

/* RET_CTRL register bit fields */
#define VBATPD4_RET_CTRL_SRAM_RSVD_FORCE_Pos (0U)
#define VBATPD4_RET_CTRL_SRAM_RSVD_FORCE_Msk (1U << VBATPD4_RET_CTRL_SRAM_RSVD_FORCE_Pos)
#define VBATPD4_RET_CTRL_SRAM_RSVD_MASK_Pos  (1U)
#define VBATPD4_RET_CTRL_SRAM_RSVD_MASK_Msk  (1U << VBATPD4_RET_CTRL_SRAM_RSVD_MASK_Pos)
#define VBATPD4_RET_CTRL_SRAM_RET1_FORCE_Pos (4U)
#define VBATPD4_RET_CTRL_SRAM_RET1_FORCE_Msk (1U << VBATPD4_RET_CTRL_SRAM_RET1_FORCE_Pos)
#define VBATPD4_RET_CTRL_SRAM_RET1_MASK_Pos  (5U)
#define VBATPD4_RET_CTRL_SRAM_RET1_MASK_Msk  (1U << VBATPD4_RET_CTRL_SRAM_RET1_MASK_Pos)
#define VBATPD4_RET_CTRL_SRAM_RET2_FORCE_Pos (8U)
#define VBATPD4_RET_CTRL_SRAM_RET2_FORCE_Msk (1U << VBATPD4_RET_CTRL_SRAM_RET2_FORCE_Pos)
#define VBATPD4_RET_CTRL_SRAM_RET2_MASK_Pos  (9U)
#define VBATPD4_RET_CTRL_SRAM_RET2_MASK_Msk  (1U << VBATPD4_RET_CTRL_SRAM_RET2_MASK_Pos)
#define VBATPD4_RET_CTRL_SRAM_RET3_FORCE_Pos (12U)
#define VBATPD4_RET_CTRL_SRAM_RET3_FORCE_Msk (1U << VBATPD4_RET_CTRL_SRAM_RET3_FORCE_Pos)
#define VBATPD4_RET_CTRL_SRAM_RET3_MASK_Pos  (13U)
#define VBATPD4_RET_CTRL_SRAM_RET3_MASK_Msk  (1U << VBATPD4_RET_CTRL_SRAM_RET3_MASK_Pos)

/* PWR_CTRL register bit fields */
#define VBATPD4_PWR_CTRL_PPU_BYPASS_Pos (4U)
#define VBATPD4_PWR_CTRL_PPU_BYPASS_Msk (0x11 << VBATPD4_PWR_CTRL_PPU_BYPASS_Pos)

typedef struct
{
    volatile const uint32_t RESERVED;  /* 0x00 */
    volatile uint32_t SEL_AUDIO_PLL;   /* 0x04 */
    volatile uint32_t ANA_REG_SEL;     /* 0x08 */
    volatile const uint32_t RESERVED1; /* 0x0C */
    volatile const uint32_t RESERVED2; /* 0x10 */
    volatile uint32_t SEL_FAST_APB;    /* 0x14 */
    volatile uint32_t VBAT_RST_SYN;    /* 0x18 */
} VBATSEC2_Type;

/* SEL_AUDIO_PLL register bit fields */
#define VBATSEC2_SEL_AUDIO_PLL_Pos (0U)
#define VBATSEC2_SEL_AUDIO_PLL_Msk (1U << VBATSEC2_SEL_AUDIO_PLL_Pos)

/* ANA_REG_SEL register bit fields */
#define VBATSEC2_ANA_REG_SEL_Pos (0U)
#define VBATSEC2_ANA_REG_SEL_Msk (1U << VBATSEC2_ANA_REG_SEL_Pos)

/* SEL_FAST_APB register bit fields */
#define VBATSEC2_SEL_FAST_APB_Pos (0U)
#define VBATSEC2_SEL_FAST_APB_Msk (1U << VBATSEC2_SEL_FAST_APB_Pos)

/* VBAT_RST_SYN register bit fields */
#define VBATSEC2_VBAT_RST_SYN_POR_Pos        (0U)
#define VBATSEC2_VBAT_RST_SYN_POR_Msk        (1U << VBATSEC2_VBAT_RST_SYN_POR_Pos)
#define VBATSEC2_VBAT_RST_SYN_BROWN_OUT_Pos  (1U)
#define VBATSEC2_VBAT_RST_SYN_BROWN_OUT_Msk  (1U << VBATSEC2_VBAT_RST_SYN_BROWN_OUT_Pos)
#define VBATSEC2_VBAT_RST_SYN_LPGPIO_RST_Pos (2U)
#define VBATSEC2_VBAT_RST_SYN_LPGPIO_RST_Msk (1U << VBATSEC2_VBAT_RST_SYN_LPGPIO_RST_Pos)
#define VBATSEC2_VBAT_RST_SYN_JTAG_NSRST_Pos (3U)
#define VBATSEC2_VBAT_RST_SYN_JTAG_NSRST_Msk (1U << VBATSEC2_VBAT_RST_SYN_JTAG_NSRST_Pos)

#define VBATALL  ((VBATALL_Type *)VBATALL_BASE)
#define VBATSEC  ((VBATSEC_Type *)VBATSEC_BASE)
#define VBATPD4  ((VBATPD4_Type *)VBATPD4_BASE)
#define VBATSEC2 ((VBATSEC2_Type *)VBATSEC2_BASE)